language: minimal
services:
- docker
fail_fast: true
before_install:
- openssl aes-256-cbc -K $encrypted_3eb3d26b78a7_key -iv $encrypted_3eb3d26b78a7_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- chmod 600 ./deploy_key
- eval "$(ssh-agent -s)"
- DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add ./deploy_key </dev/null
script:
- eval "export $(cat .env | xargs)"
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build . -t patrixr/tronica
- docker push patrixr/tronica
- echo "${DOCKER_HOST}"
- docker-compose down
- docker-compose pull
- docker-compose up -d
env:
  matrix:
  - secure: ZwJ9JNYC5pxETifo07X9xMCbmXwGcPpkcZ/Lj+TGZ/2R/uDTizP7oVO7VAbOxN3zoqDRrMnZlhFr0FweNpzr/DHeak3cKsTi6Nu9jz20nb+5NiZxeQz5FoUwwM1dbsvL/Hkc+CvMYvQ6QNVtll5/RV1Oa/GT7jlnTXhp5DZqgQC6hy7/0rQkZ1GmHAyaO8CISP4xUYiRPbCQA20l/97sB0QAO0mpdunXG+L9EgHr+knR8zUsmK1ieQGvIgzpVTZbznTwn9rZ8Hz4rrJt08bKyZCuSZyBrHlKscQR6OskXvvyRUjEJb5989C3hMViKlYdb8YxhccJgiVEdZw74Z4rQtD22a//wLpVcAYTAUF3Fz4CdebmWzgzTIZ2IspzOlJwU1taj2pKsokrs7slXfQuxSGRrhZi4FVzdFOeFN67g6EXOdnvoZi5UB+TsVBQdn2qSDdp3+4IuXbzCOwG7Vfm949jEcyK3j+LL1udVn8UFZD1Dh4RJKDzwAaTvuoTfGNIbJE+rTqqQaoh9tPZo6oMc4hoMFxnWmAPWYFLq1cBEzSo9UPB/TP2zC8AYRJD+ncizjAeWRflXB0IlSD6McwSsj7tPfWr28cEya4PVcPV5Q2Qhj6hdZsWVXoyOn/pfqV+DuR79BDWxJa3BoRCUy7Ef7jfraXkJi4enjXzCSdqkoE=
  - secure: dc9sjXHmHbYpZakzf9EkCScOllRNI4r1hlsp/esQCKBo/knHvYV5gbuzsHRN6suO2iVOYQAYxzIyyL5xaiQa2rYKYoBnw2exVcFJPPhmWxJ4uwFxRDId6MoXEErOjx+MOCz61nSn2wArxELlHdH3nr0v2i2saD5caTJ9tVkJTDA+divbDUdG0Z4NceUdpT/4kL1fZKSuAO7WxvEk7mgxrIPWtrWPWqjbHZcInbUVoEABMYcTQKEHSPzh9L9VKy6MtUqFJi2IjU4atDe7J8hdWGmziZstONKnvRO5fh3hJr96fXOgdvuvfQp+GQujYg34e9aUswG8nO7cujk4Yw5zRGLItgJxP8THQIkeNNgcnPhkHWsQCd2z/jWxvg5qWJkN9L2WDIjWfCFpMgBN7Bz4bsDgbuskSLFZ54UELCNJb68sL0HeEwdLxET39gl0tt4nM6IWSpi8QJOgt/paUe7x2ycWAIplfOWxgy7C3f2wHsJZYFO4wacrTbkzPRM1M+EkP0A1mHCsAn1P7VSzKOBkZE2h+S86eER+hTD7KUiRrv9+84WRVhINEPy4dCd5bKT9I4U6MglfXy99I8/AO2nD2MFO/4YJ2XbFa1aucCSetMDE6aOSyuu45J8Ak5uNO9axh+QNcbZq+F014O4qvn/nvU+Q4+QtCBOCBhD/jx5Czvo=
  - secure: DiZswpHeqKMfJ67r7giu8zkN0Rorc0R2Z/8sBirR4schEDgaD9k+6hIhJZP43l7E9wM++ysOnyatRrvJo1roxjnAj7i0U9RqZBVxvNzIChC2pXLvTRr2Kg0Va9W70ckXkTr76tCzg1OMosVegykf5I2hdJCGS0WjFSSEVTZAXgj3TGvTdLTOXyKIi9sXflLOQ/YrQ7O2qYnQqSoMnJ13Vt6lL0iJ84YS/oyrJ/UyclwZ7muOIJcXNLTcdzJ2yjT7MOfWXPQqEQJEZROJJ+j4//xGbsmackBJ/evbxUXeQjBQvlnqbmH3CSJc1n74zkxDBXLA7tFS0JRuiFR/INJVvKWyodRAy28SYWiWo0EQYe4JDUa2jnSyijuc9vX9saEakPAY/wyxPnLwM6FxlUfgby8ZsUS0ORqBeQcZYa2QV/5nCqRR/K3RPafg1hktacd34pLCcznTbRA8MmgyV3EdGO+w7cg1Ozam04Oy4SB92KNHVBU4ArXoLQUa5bxujYO8NoiHxnkGlyuQPUiKIbEBj/ZF0eQVrWqZC3sHWzlVSCVWo2gdFwrJJkF2xKsYQWluWWdG6+GfLxuDrK2WoVdUsAt1eaOr9JU9Ap4zKRaDaYL8+upLj2d2AK0efuIdeeBWc81Krs9f34YzezOpAPbhTk0YB/yW8UKu3mouO/MsiRc=
