version: "3.3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /opt/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tronica_blog
      MYSQL_USER: tronica
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  ghost:
    image: patrixr/tronica:latest
    restart: always
    ports:
      - "2368:2368"
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: tronica
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: tronica_blog
    depends_on:
      - mysql

  nginx:
    image: nginx:1.17-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx/websites:/etc/nginx/conf.d
      - /opt/nginx/certbot/conf:/etc/letsencrypt
      - /opt/nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - /opt/nginx/certbot/conf:/etc/letsencrypt
      - /opt/nginx/certbot/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"