version: "3.3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /opt/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tronica_blog
      MYSQL_USER: tronica
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  ghost:
    image: patrixr/tronica:latest
    restart: always
    ports:
      - "2368:2368"
    environment:
      VIRTUAL_HOST: "*.tronica.io"
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: tronica
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: tronica_blog
    depends_on:
      - mysql

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/nginx/certs:/etc/nginx/certs
      - /opt/nginx/vhost.d:/etc/nginx/vhost.d
      - /opt/nginx/html:/usr/share/nginx/html

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /opt/nginx/vhost.d:/etc/nginx/vhost.d
      - /opt/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/nginx/html:/usr/share/nginx/html