---
version: "3.7"
services:
  ghost:
    image: patrixr/tronica:latest
    restart: always
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: tronica
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: tronica_blog

 mysql:
  image: mysql:5.7
  restart: always
  container_name: mysql
  volumes:
    - mysql-volume:/var/lib/mysql
  environment:
    MYSQL_DATABASE: tronica_blog
    MYSQL_USER: tronica
    MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    MYSQL_PASSWORD: ${DB_PASSWORD}